# Generated by Django 6.0.2 on 2026-02-25 20:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Authors",
        ),
        migrations.RenameModel(
            old_name="Book",
            new_name="Books",
        ),
    ]
