# Generated by Django 6.0.2 on 2026-02-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_author_authors_rename_book_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
