# Generated by Django 6.0.2 on 2026-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_rename_genre_book_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
