# Generated by Django 6.0.2 on 2026-02-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books_written',
        ),
    ]
