# Generated by Django 6.0.2 on 2026-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_remove_author_books_written"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="most_famous_book",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
