# Generated by Django 6.0.2 on 2026-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_author_most_famous_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='plot',
            field=models.TextField(blank=True),
        ),
    ]
