# Generated by Django 6.0.2 on 2026-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
